title: Radha Sowjanya Chitta
logo: /assets/img/logo.png
description:
  <p align="center">
    <a href="https://github.com/radhasowjanya">GitHub</a>
  
  <br>   
  I'm working on Data Science, Machine learning & NLP related problems.
  <br>
  </p>


theme: jekyll-theme-minimal
